version: "3"
services:
  db:
    image: "postgres"
    restart: "no"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=changeme
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - .:/docker-entrypoint-initdb.d:delegated

  filebin:
    build: .
    restart: "no"
    environment:
      - DB_NAME=db
      - DB_USERNAME=username
      - DB_PASSWORD=changeme
    expose:
      - "8888"
    ports:
      - "8888:8888"
    volumes:
      - .:/app:delegated
    depends_on:
      - db
    entrypoint: ["make"]

