version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
      - image: circleci/postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=changeme
    steps:
      - checkout
      - run: ls
      - run: echo "A first hello"
